sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: rootpassword
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: xxxxxxxxx
    access-key-secret: xxxxxxxxx
    bucket-name: xxxxxxxxx
  redis:
    host: localhost
    port: 6379
    password: xxxxxxxxx
    database: 10
  wechat:
    appid: xxxxxxxxx
    secret: xxxxxxxxx
  proxy:
    host: 127.0.0.1
    port: 7890
  ai:
    openai:
      api-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
